### ISSUE TITLE
ItemNotFound Exception for CodeInspection_9.xml

### ISSUE THREAD

**Issue by shahrouzmohaghegh** [alanwales/vsts-resharper-code-quality-task#14]
I get ItemNotFoundException for CodeInspection_9.xml file:

2018-05-03T05:08:20.8697803Z No pre-installed Resharper CLT was found, downloading the latest from nuget.org...
2018-05-03T05:08:44.4981487Z Resharper CLT downloaded
2018-05-03T05:08:44.5355725Z Inspecting code for "D:\a\1\s\NetCoreApp"
2018-05-03T05:08:44.5356269Z Invoking InspectCode.exe using arguments "D:\a\1\s\NetCoreApp" /o:"D:\a\1\a\JetBrains.ReSharper.CommandLineTools.2018.1.0\tools\Reports\CodeInspection_9.xml" /disable-settings-layers:SolutionPersonal
 
2018-05-03T05:08:56.8980764Z ##[error]System.Management.Automation.ItemNotFoundException: Cannot find path 'D:\a\1\a\JetBrains.ReSharper.CommandLineTools.2018.1.0\tools\Reports\CodeInspection_9.xml' because it does not exist.

**Comment by lennartb-** [comment]
Same issue here, began to happen on May 21st.

`System.Management.Automation.ItemNotFoundException: Der Pfad "C:\agent\_work\6\a\JetBrains.ReSharper.CommandLineTools.2018.1.2\tools\Reports\CodeInspection_7382.xml" kann nicht gefunden werden, da er nicht vorhanden ist.`

**Comment by lennartb-** [comment]
Seems to be solved with installing the .NET Core workload for the Build Tools on the agent. Running the inspectcode.exe call locally with the arguments supplied by the logging output gave me the actual error.

**Comment by bobvandevijver** [comment]
So, apparently this is caused by VSTS (powershell?) checking the given path to rigiously: it expects that path gives as arguments in the `Start-Process` call are all existent. This means it isn't necessarily related to this plugin, but it might be possible to solve it in the script.

Anyways, for now we've added a simple bash script, which creates the output file before running the analysis task. 

So, the Bash script, run in `$(Common.TestResultsDirectory)` 
```
touch resharper_analysis.xml
``` 
with `$(Common.TestResultsDirectory)\resharper_analysis.xml` as "Results output file path" in this plugin works.

**Comment by bobvandevijver** [comment]
Worked. It has broken again now.

**Comment by bobvandevijver** [comment]
So, the solution above worked, but stopped working about 3 weeks ago (without any changes from my end). 

However, Jetbrains has made now made a statement: the tooling requires MSBuildTools to be installed, which I did not have. See:
- https://resharper-support.jetbrains.com/hc/en-us/community/posts/360000512619-Resharper-CLT-inspectcode-on-net-core-project
- https://youtrack.jetbrains.com/issue/RSRP-470097

For now, I've solved it for my dotnet core 2.1 project by using the "Hosted VS2017" agent, with the steps below:

![screen shot 2018-09-26 at 10 16 44](https://user-images.githubusercontent.com/1835343/46066644-4f442300-c175-11e8-8887-0b2866de7ca9.png)

**Comment by SantGitHub0802** [comment]
Hi Team,
I am using .Net desktop application and Hosted VS2017 as agent. It is throwing the same type of error "ItemNotFoundException for CodeInspection_9.xml file" in Azure devops build.Please let me if anyone have solution for this issue.

**Comment by bobvandevijver** [comment]
Currently, I use this, as I hit some errors with the NuGet restore combined with dotnet core projects.

![screen shot 2019-01-23 at 14 04 34](https://user-images.githubusercontent.com/1835343/51608494-ecdb1380-1f17-11e9-862b-dcb21ef1e124.png)

I no longer have the script to create the output file, but I do still use `$(Common.TestResultsDirectory)\$(Resharper.Output.File)` as "Results output file path
".

**Comment by SantGitHub0802** [comment]
The above solution still not working for me in Azure DevOps build pipeline.I am getting the same error.

**Comment by SantGitHub0802** [comment]
Hi,
I have also tried by writing power shell script to create empty outputfile.xml in specific path and verified the file exists in that path after that.It works well.Then specified the same path in Results path. But after then, ReSharper throws the same error "path does not exists" by saying the same path i created.
Please provide me some solution to resolve this issue.

**Comment by jcast07** [comment]
Hi,
Is the problem described above due to .Net Core? I tried using PowerShell scripts to do the inspection, since I am getting the same error as others and got the following error:
The default XML namespace of the project must be the MSBuild XML namespace.....

Has anyone found a solution.

**Comment by bobvandevijver** [comment]
I cannot create a complete export due to configuration and overhead reasons, but this is what works for me on several .NET Core 2.2 projects at this moment.

The configuration is the same as I posted [earlier](https://github.com/alanwales/vsts-resharper-code-quality-task/issues/14#issuecomment-456794690), which contain the default 'Use .NET Core SDK' and 'dotnet restore' tasks. But, **make sure to use the **Hosted VS2017** runner for your configuration, as it has the required dependencies for the ReSharper tooling to work.**

Below is the full configuration export of the ReSharper task:
```yaml
steps:
- task: alanwales.resharper-code-analysis.custom-build-task.ResharperCli@1
  displayName: 'Resharper Code Quality Analysis'
  inputs:
    SolutionOrProjectPath: '$(solution.file)'
    ResultsOutputFilePath: '$(Common.TestResultsDirectory)\$(Resharper.Output.File)'
```

**Comment by jcast07** [comment]
@bobvandevijver thanks,  but I can only use a self hosted agent. Do you know what are the required dependencies?

**Comment by alanwales** [comment]
As far as I am aware the Resharper CLT only works on Windows machines with the correct dependencies installed:

https://resharper-support.jetbrains.com/hc/en-us/community/posts/360000018359-ReSharper-CLT-on-Linux

I have always used the Hosted VS2017 agent on Azure Devops and never had issues. I suspect a lot of the 1* reviews are using self-hosted agents without the required dependencies installed or even Linux agents... but due to the volume of bad reviews I gave up supporting this extension a while ago.

Basically whatever the Resharper CLT requires will work with this task as it’s just a wrapper around it with Powershell (not Powershell Core, it wouldn’t work anyway as a wrapper because the Resharper CLT is not cross-platform).

I would advise anyone to switch in the long-run to the .editorconfig rules. This is not yet supported on CI systems but I have seen a Github work item which says this is in progress. It’s about time Visual Studio decoupled code style rule enforcement from the IDE but it’s not here yet.

I am using Rider at the moment but plan to switch back to Visual Studio when the native refactoring capabilities gets to the same level (not the case with VS 2019). Also JetBrains were rather draconian with their copyright enforcement for this task so that’s another reason I had enough of supporting it.

.editorconfig is the future so please check it out

https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019

**Comment by jcast07** [comment]
Hi,

I was able to solve my issue by installing Visual Studio 2017 on the machine running the self hosted agent.

**Comment by alanwales** [comment]
I just had a project where we use the Yaml pipelines so had a chance to fix this issue finally.

The issue is that the .Net Core installer task installs the .Net Core SDK in a location which the Resharper Command-Line Tooks cannot resolve. You will need to add the "MSBuildSDKsPath" environment variable to the task as shown in the Yaml sample on https://marketplace.visualstudio.com/items?itemName=alanwales.resharper-code-analysis

`         env:
          MSBuildSDKsPath: '$(Agent.ToolsDirectory)/dncs/$(DotNet.Sdk.Version)/x64/sdk/$(DotNet.Sdk.Version)/Sdks'
`

The task is working with the latest .net core 3.0 preview
